class ScrapedFixes:
    def fixLanguage(self):
        replace = {
            "EN": "English",
            "FR": "French",
            "HE": "Hebrew",
            "HEB": "Hebrew",
            "CZ": "Czech",
            "KO": "Korean",
            "GER": "German",
            "JAP": "Japanese",
            "DAN": "Danish",
            "RU": "Russian",
            "אנגלית": "English",
            "עברית": "Hebrew",
            "דנית": "Danish",
            "צרפתית": "French",
            "גרמנית": "German",
            "הינדי": "Hindi",
            "יפנית": "Japanese",
            "יעודכן בקרוב": None,
        }
        self.original_language = replace.get(self.original_language, self.original_language)

    def fixRating(self):
        replace = {
            "No limit": "All",
            "מותר לכל": "All",
            "הותר לכל": "All",
            "מותר לכל הגילאים": "All",
            "הגבלת גיל: הותר לכל הגילאים": "All",
            "Allowed for all ages": "All",
            "הותר מגיל 18": "18+",
            "הגבלת גיל: הותר מגיל 16 בהצגת תעודה מזהה": "16+",
            "הותר מגיל 16": "16+",
            "הגבלת גיל: הותר מגיל 14": "14+",
            "הותר מגיל 14": "14+",
            "הגבלת גיל: הותר מגיל 12": "12+",
            "הותר מגיל 12": "12+",
            "הותר מגיל 9": "9+",
            "עד גיל 8 בליווי מבוגר": "9+",
            "Other": None,
            "אחר": None,
            "יעודכן בקרוב": None,
            "הגבלת גיל: טרם נקבע": None,
            "טרם נקבע": None,
            "": None,
        }
        self.rating = replace.get(self.rating, self.rating)

    def fixCinemaName(self):
        replace = {
            "Lev Smadar": "Jerusalem",
            "Lev Omer": "Omer",
            "Even Yehuda": "Even Yehuda",
            "Ramat Hasharon": "Ramat Hasharon",
            "Lev Raanana": "Raanana",
            "Lev Shoham": "Shoham",
            "Lev Daniel": "Herziliya",
            "לוח הקרנות ב רב חן גבעתיים": "Givatayim",
            "לוח הקרנות ב רב חן דיזינגוף": "Tel Aviv",
            "לוח הקרנות ב רב חן קרית אונו": "Kiryat Ono",
            "SCREENINGS FOR PLANET BEER SHEVA": "Beer Sheva",
            "SCREENINGS FOR PLANET AYALON": "Ayalon",
            "SCREENINGS FOR PLANET RISHON LETZIYON": "Rishon Letzion",
            "SCREENINGS FOR PLANET ZICHRON YAAKOV": "Zichron Yaakov",
            "SCREENINGS FOR PLANET JERUSALEM": "Jerusalem",
            "SCREENINGS FOR PLANET HAIFA": "Haifa",
            "כרמיאל": "Carmiel",
            "חיפה": "Haifa",
            "נתניה": "Netanya",
            'הצוק ת"א': "Glilot",
            "עפולה": "Afula",
            'עזריאלי ת"א Summer Sky': "Azrieli Rooftop",
            "HOT CINEMA כרמיאל": "Carmiel",
            "HOT CINEMA נהריה": "Nahariya",
            "HOT CINEMA קריון": "Kiryat Bialik",
            "HOT CINEMA חיפה": "Haifa",
            "HOT CINEMA כפר סבא": "Kfar Saba",
            "HOT CINEMA פתח תקווה": "Petach Tikvah",
            "HOT CINEMA מודיעין": "Modiin",
            "HOT CINEMA רחובות": "Rehovot",
            "HOT CINEMA אשדוד": "Ashdod",
            "HOT CINEMA אשקלון": "Ashkelon",
            "סינמה סיטי גלילות": "Glilot",
            "סינמה סיטי גלילות": "Glilot",
            "סינמה סיטי גלילות (ONYX)": "Glilot",
            "סינמה סיטי גלילות (VIP)": "Glilot",
            "סינמה סיטי גלילות (Lounge)": "Glilot",
            'סינמה סיטי ראשל"צ': "Rishon Letzion",
            'סינמה סיטי ראשל"צ (VIP)': "Rishon Letzion",
            'סינמה סיטי ראשל"צ (VIP לייט)': "Rishon Letzion",
            "סינמה סיטי ירושלים": "Jerusalem",
            "סינמה סיטי ירושלים (VIP)": "Jerusalem",
            "סינמה סיטי כפר-סבא": "Kfar Saba",
            "סינמה סיטי כפר סבא (Prime)": "Kfar Saba",
            "סינמה סיטי נתניה": "Netanya",
            "סינמה סיטי נתניה (Prime)": "Netanya",
            "סינמה סיטי באר שבע": "Beer Sheva",
            "סינמה סיטי באר שבע (VIP)": "Beer Sheva",
            "סינמה סיטי אשדוד": "Ashdod",
            "סינמה סיטי חדרה": "Chadera",
            "סינמה סיטי חדרה (Prime)": "Chadera",
        }
        self.screening_city = replace.get(self.screening_city, self.screening_city)

    def fixScreeningType(self):
        replace = {
            "רגיל": "Regular",
            "ONYX": "Regular",
            "VIP": "VIP",
            "VIP לייט": "VIP Light",
            "VIP ביזנס": "VIP Business",
            "Prime": "Prime",
            "סינמה סיטי גלילות (Lounge)": "Lounge",
            "סינמה סיטי גלילות (VIP)": "VIP",
            'סינמה סיטי ראשל"צ (VIP)': "VIP",
            'סינמה סיטי ראשל"צ (VIP לייט)': "VIP Light",
            "סינמה סיטי ירושלים (VIP)": "VIP",
            "סינמה סיטי כפר סבא (Prime)": "Prime",
            "סינמה סיטי נתניה (Prime)": "Prime",
            "סינמה סיטי באר שבע (VIP)": "VIP",
            "סינמה סיטי חדרה (Prime)": "Prime",
            "2D רגיל": "Regular",
            "3D רגיל": "Regular",
            "2D HFR רגיל": "Regular",
            "3D HFR רגיל": "Regular",
            "2D VIP": "VIP",
            "3D VIP": "VIP",
            "2D HFR VIP": "VIP",
            "3D HFR VIP": "VIP",
            "2D ONYX": "Regular",
            "3D ONYX": "Regular",
            "2D HFR ONYX": "Regular",
            "3D HFR ONYX": "Regular",
            "2D Lounge": "Lounge",
            "3D Lounge": "Lounge",
            "2D HFR Lounge": "Lounge",
            "3D HFR Lounge": "Lounge",
            "2D Prime": "Prime",
            "3D Prime": "Prime",
            "2D HFR Prime": "Prime",
            "3D HFR Prime": "Prime",
            "SCREENX3D": "Regular",
            "SCREENX2D": "Regular",
            "2DIMAX": "Regular",
            "3DIMAX": "Regular",
            "SCREENX": "Regular",
            "4DX3D": "Regular",
            "4DX2D": "Regular",
            "3D4DX": "Regular",
            "2D4DX": "Regular",
            "4DX": "Regular",
            "3D": "Regular",
            "2D": "Regular",
            "3DDOLBY ATMOS": "Regular",
            "2DDOLBY ATMOS": "Regular",
            "IMAX3D": "Regular",
            "2DSCREENX": "Regular",
            "3DSCREENX": "Regular",
            "VIP2D": "VIP",
            "VIP3D": "VIP",
            "VIP LIGHT2D": "VIP Light",
            "VIP LIGHT3D": "VIP Light",
        }
        self.screening_type = replace.get(self.screening_type, self.screening_type)

    def fixScreeningTech(self):
        replace = {
            "סינמה סיטי גלילות": "2D",
            "סינמה סיטי גלילות (ONYX)": "2D ONYX",
            'סינמה סיטי ראשל"צ': "2D",
            "סינמה סיטי ירושלים": "2D",
            "סינמה סיטי כפר-סבא": "2D",
            "סינמה סיטי נתניה": "2D",
            "סינמה סיטי באר שבע": "2D",
            "סינמה סיטי אשדוד": "2D",
            "סינמה סיטי חדרה": "2D",
            "2D רגיל": "2D",
            "3D רגיל": "3D",
            "2D HFR רגיל": "2D HFR",
            "3D HFR רגיל": "3D HFR",
            "2D VIP": "2D",
            "3D VIP": "3D",
            "2D HFR VIP": "2D HFR",
            "3D HFR VIP": "3D HFR",
            "2D ONYX": "2D ONYX",
            "3D ONYX": "3D ONYX",
            "2D HFR ONYX": "2D HFR ONYX",
            "3D HFR ONYX": "3D HFR ONYX",
            "2D Lounge": "2D",
            "3D Lounge": "3D",
            "2D HFR Lounge": "2D HFR",
            "3D HFR Lounge": "3D HFR",
            "2D Prime": "2D",
            "3D Prime": "3D",
            "2D HFR Prime": "2D HFR",
            "3D HFR Prime": "3D HFR",
            "ONYX": "2D ONYX",
            "VIP": "2D",
            "SCREENX3D": "3D ScreenX",
            "SCREENX2D": "2D ScreenX",
            "2DIMAX": "2D IMAX",
            "3DIMAX": "3D IMAX",
            "SCREENX": "2D ScreenX",
            "4DX3D": "3D 4DX",
            "4DX2D": "2D 4DX",
            "3D4DX": "3D 4DX",
            "2D4DX": "2D 4DX",
            "4DX": "2D 4DX",
            "3D": "3D",
            "2D": "2D",
            "3DDOLBY ATMOS": "3D Atmos",
            "2DDOLBY ATMOS": "2D Atmos",
            "IMAX3D": "3D IMAX",
            "2DSCREENX": "2D ScreenX",
            "3DSCREENX": "3D ScreenX",
            "VIP2D": "2D",
            "VIP3D": "3D",
            "VIP LIGHT2D": "2D",
            "VIP LIGHT3D": "3D",
        }
        self.screening_tech = replace.get(self.screening_tech, self.screening_tech)
